import test from 'node:test';
import assert from 'node:assert/strict';
import {postmortemSections,postmortemMarkdown,postmortemHtml} from '../src/data/postmortemContent.ts';
const evidence=[{id:'E01',type:'METRICS',title:'Pool at capacity',source:'Prometheus',detail:'100/100 connections',state:'Supports hypothesis'}];
test('comprehensive report includes the full lifecycle and timeline',()=>{const sections=postmortemSections('Edited summary','Approved after review',evidence);assert.equal(sections.length,5);for(const id of ['summary','timeline','findings','recovery','actions'])assert.ok(sections.some(s=>s.id===id));const timeline=sections.find(s=>s.id==='timeline');assert.ok(timeline.rows.some(r=>r[0]==='09:42–09:44'));assert.ok(timeline.rows.some(r=>r[0]==='09:50–10:00'));assert.equal(sections.find(s=>s.id==='findings').rows.length,1);});
test('markdown exports edited summary, decision reason, evidence, and review state',()=>{const md=postmortemMarkdown(postmortemSections('Edited summary','Canary reviewed',evidence),true);for(const text of ['Edited summary','Canary reviewed','E01','Reviewed in prototype','Response progress','Lessons & follow-up actions'])assert.ok(md.includes(text));});
test('formatted HTML escapes user-authored content and retains all section titles',()=>{const sections=postmortemSections('<script>alert(1)</script>','<b>reason</b>',evidence);const html=postmortemHtml(sections,false);assert.ok(!html.includes('<script>'));assert.ok(html.includes('&lt;script&gt;'));assert.ok(html.includes('&lt;b&gt;reason'));for(const s of sections)assert.ok(html.includes(s.title.replaceAll('&','&amp;')));assert.ok(html.includes('@media print'));});

test("review milestone follows document review state",()=>{const draft=postmortemSections("Summary","Reason",evidence,false);const reviewed=postmortemSections("Summary","Reason",evidence,true);assert.equal(draft.find(s=>s.id==="timeline").rows.at(-1)[3],"Awaiting review");assert.equal(reviewed.find(s=>s.id==="timeline").rows.at(-1)[3],"Reviewed");assert.ok(postmortemHtml(draft,false).includes('class="progress"'));});
