import { useState } from 'react';
import { Button, TextField, MenuItem, TableContainer, Table, TableHead, TableBody, TableRow, TableCell, Dialog, DialogTitle, DialogContent, DialogActions } from '@mui/material';
import { DownloadRounded, AddRounded, EditOutlined, ShieldOutlined } from '@mui/icons-material';
import { incidentRows } from '../data/incidents';
import { canManage, reportRows, groupReport, csvCell } from '../utils/access';
import type { AirRole, SystemConfig } from '../utils/access';

type Props={role:AirRole;page:string;recovered:boolean;systems:SystemConfig[];onSave:(config:SystemConfig)=>void};
export function CommanderPage({role,page,recovered,systems,onSave}:Props){
 const [system,setSystem]=useState('All');const [status,setStatus]=useState('All');const [from,setFrom]=useState('2026-09-01');const [to,setTo]=useState('2026-09-07');const [groupBy,setGroupBy]=useState<'System'|'Status'|'Date'>('System');
 const [draft,setDraft]=useState<SystemConfig|null>(null);const [editing,setEditing]=useState(false);const [message,setMessage]=useState('');
 if(!canManage(role))return <div className="air-card"><h2>Incident Commander access required</h2><p>System configuration and incident analytics are available to Incident Commanders.</p></div>;
 const rows=incidentRows.map(r=>r.id==='INC-2048'&&recovered?{...r,status:'Resolved'}:r);
 const filtered=reportRows(rows,system,status,from,to);const groups=groupReport(filtered,groupBy);const invalidDate=Boolean(from&&to&&from>to);
 const duplicate=Boolean(draft&&!editing&&systems.some(s=>s.id===draft.id.trim()));
 const valid=Boolean(draft&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(draft.id)&&draft.name.trim()&&draft.owner.trim()&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(draft.slackPrefix)&&!duplicate);
 const exportReport=()=>{if(invalidDate||!canManage(role))return;const lines=[['AIR incident report — synthetic demo data'],['Generated at (UTC)',new Date().toISOString()],['System',system,'Status',status,'From (UTC)',from||'Any','Through (UTC)',to||'Any'],[],[groupBy,'Total incidents','Open incidents','Resolved incidents'],...groups.map(g=>[g.label,String(g.total),String(g.open),String(g.resolved)]),[],['Incident ID','Title','System','Status','Severity','Declared at (UTC)','Owner'],...filtered.map(r=>[r.id,r.title,r.service,r.status,r.severity,r.openedAt,r.owner])];const blob=new Blob(['\uFEFF'+lines.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='AIR-incident-report.csv';a.click();URL.revokeObjectURL(url);setMessage(`Report generated with ${filtered.length} incidents and ${groupBy.toLowerCase()} summary.`);};
 return <><div className="ops-heading"><div><span className="air-eyebrow">INCIDENT COMMANDER WORKSPACE</span><h1>{page}</h1><p>{page==='Analytics'?'Understand incident history by system, status, and date.':'Manage the systems AIR monitors and their response ownership.'}</p></div><span className="ops-live"><ShieldOutlined fontSize="small"/> Commander access · demo</span></div>
 {page==='Analytics'?<>
 <section className="air-card"><div className="air-section-title"><h3>Report scope</h3><Button variant="contained" startIcon={<DownloadRounded/>} disabled={invalidDate||filtered.length===0} onClick={exportReport}>Generate CSV report</Button></div><div className="air-report-filters"><TextField select size="small" label="System" value={system} onChange={e=>setSystem(e.target.value)}><MenuItem value="All">All systems</MenuItem>{systems.map(s=><MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</TextField><TextField select size="small" label="Incident status" value={status} onChange={e=>setStatus(e.target.value)}>{['All','Declared','Investigating','Monitoring','Resolved'].map(s=><MenuItem key={s} value={s}>{s==='All'?'All statuses':s}</MenuItem>)}</TextField><TextField type="date" size="small" label="From (UTC)" value={from} onChange={e=>setFrom(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" size="small" label="Through (UTC)" value={to} onChange={e=>setTo(e.target.value)} error={invalidDate} helperText={invalidDate?'End date must be on or after start date.':undefined} slotProps={{inputLabel:{shrink:true}}}/><TextField select size="small" label="Group report by" value={groupBy} onChange={e=>setGroupBy(e.target.value as typeof groupBy)}>{['System','Status','Date'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></div><p className="air-config-note">Dates use incident declaration time, inclusive of both dates. Status reflects the current demo snapshot.</p></section>
 <div className="ops-metrics air-report-metrics">{[['Total incidents',filtered.length],['Open incidents',filtered.filter(r=>r.status!=='Resolved').length],['Resolved incidents',filtered.filter(r=>r.status==='Resolved').length],['Affected systems',new Set(filtered.map(r=>r.service)).size]].map(([label,value])=><div className="ops-metric" key={label}><span>{label}</span><strong>{invalidDate?'—':value}</strong></div>)}</div>
 <section className="ops-table-panel"><div className="ops-panel-heading"><h2>Incidents by {groupBy.toLowerCase()}</h2><span className="ops-live">{filtered.length} matching incidents</span></div><TableContainer><Table aria-label="Incident analytics summary"><TableHead><TableRow>{[groupBy,'Distribution','Total','Open','Resolved'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{groups.map(g=><TableRow key={g.label}><TableCell>{g.label}</TableCell><TableCell><div className="air-report-bar" role="img" aria-label={`${g.total} of ${filtered.length} incidents`}><span style={{width:`${g.total/Math.max(1,filtered.length)*100}%`}}/></div></TableCell><TableCell>{g.total}</TableCell><TableCell>{g.open}</TableCell><TableCell>{g.resolved}</TableCell></TableRow>)}{!groups.length&&<TableRow><TableCell colSpan={5} className="ops-empty">{invalidDate?'Correct the date range to view the report.':'No incidents match this report scope.'}</TableCell></TableRow>}</TableBody></Table></TableContainer></section>
 <section className="ops-table-panel"><div className="ops-panel-heading"><h2>Report details</h2></div><TableContainer><Table aria-label="Filtered report incidents"><TableHead><TableRow>{['Incident','System','Status','Severity','Declared (UTC)'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{filtered.map(r=><TableRow key={r.id}><TableCell><small className="ops-id">{r.id}</small>{r.title}</TableCell><TableCell>{r.service}</TableCell><TableCell>{r.status}</TableCell><TableCell>{r.severity}</TableCell><TableCell>{r.openedAt.replace('T',' ').replace('Z','')}</TableCell></TableRow>)}{!filtered.length&&<TableRow><TableCell colSpan={5} className="ops-empty">No report rows to display.</TableCell></TableRow>}</TableBody></Table></TableContainer></section>
 </>:<>
 <section className="ops-table-panel"><div className="ops-panel-heading"><h2>Configured systems <span className="ops-count">{systems.length}</span></h2><Button variant="contained" startIcon={<AddRounded/>} onClick={()=>{setEditing(false);setDraft({id:'',name:'',owner:'',environment:'Production',slackPrefix:'air-inc'});}}>Add system</Button></div><TableContainer><Table aria-label="System configuration"><TableHead><TableRow>{['System','Service key','Owner','Environment','Slack prefix','Action'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{systems.map(s=><TableRow key={s.id}><TableCell>{s.name}</TableCell><TableCell>{s.id}</TableCell><TableCell>{s.owner}</TableCell><TableCell>{s.environment}</TableCell><TableCell>#{s.slackPrefix}</TableCell><TableCell><Button size="small" startIcon={<EditOutlined/>} aria-label={`Edit ${s.name}`} onClick={()=>{setEditing(true);setDraft({...s});}}>Edit</Button></TableCell></TableRow>)}</TableBody></Table></TableContainer></section><div className="air-callout">Configuration is saved for this demo session and remains available when switching roles. It does not provision connectors, modify production systems, or create Slack channels.</div>
 </>}
 {message&&<p className="air-success" role="status">{message}</p>}
 <Dialog open={draft!==null} onClose={()=>setDraft(null)} fullWidth maxWidth="sm"><DialogTitle>{editing?'Edit system':'Add system'}</DialogTitle><DialogContent>{draft&&<div className="air-config-form"><TextField label="System name" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/><TextField label="Service key" value={draft.id} disabled={editing} onChange={e=>setDraft({...draft,id:e.target.value})} error={duplicate} helperText={duplicate?'This service key already exists.':'Lowercase letters, numbers, and single hyphens.'} required/><TextField label="Owner team" value={draft.owner} onChange={e=>setDraft({...draft,owner:e.target.value})} required/><TextField select label="Environment" value={draft.environment} onChange={e=>setDraft({...draft,environment:e.target.value})}>{['Production','Staging','Development'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField><TextField label="Slack channel prefix" value={draft.slackPrefix} onChange={e=>setDraft({...draft,slackPrefix:e.target.value})} helperText="Lowercase letters, numbers, and single hyphens. Existing channels are unchanged." required/></div>}</DialogContent><DialogActions><Button onClick={()=>setDraft(null)}>Cancel</Button><Button variant="contained" disabled={!valid} onClick={()=>{if(draft&&valid&&canManage(role)){onSave({...draft,name:draft.name.trim(),owner:draft.owner.trim()});setMessage(`${draft.name.trim()} configuration saved in this demo session.`);setDraft(null);}}}>Save configuration</Button></DialogActions></Dialog>
 </>;
}
