import { useState } from 'react';
import { TextField, MenuItem, Button, Table, TableHead, TableRow, TableCell, TableBody, TableContainer } from '@mui/material';
import { incidentRows } from '../data/incidents';
import { leadershipMetrics } from '../data/leadership';
import { groupReport, csvCell } from '../utils/access';
import type { SystemConfig } from '../utils/access';
const colors=['#006fcf','#00175a','#66a9e2','#008767'];
export function LeadershipPage({recovered,systems}:{recovered:boolean;systems:SystemConfig[]}){
 const [status,setStatus]=useState('All');const [groupBy,setGroupBy]=useState<'System'|'Status'|'Date'>('System');const [notice,setNotice]=useState('');
 const [from,setFrom]=useState('2026-09-01');const [to,setTo]=useState('2026-09-08');const [system,setSystem]=useState('All');const [statusChart,setStatusChart]=useState('Donut');const [trendChart,setTrendChart]=useState('Bars');
 const rows=incidentRows.map(r=>({...r,status:r.id==='INC-2048'&&recovered?'Resolved':r.status,resolvedAt:r.id==='INC-2039'?'2026-09-06T16:32:00Z':r.id==='INC-2048'&&recovered?'2026-09-07T10:00:00Z':null})).filter(r=>(system==='All'||r.service===system)&&(status==='All'||r.status===status));
 const m=leadershipMetrics(rows,from,to);const cohort=m?rows.filter(r=>r.openedAt.slice(0,10)>=from&&r.openedAt.slice(0,10)<=to):[];
 const groups=groupReport(cohort,groupBy);
 const exportReport=()=>{if(!m||to>'2026-09-08'||!rows.length)return;const data=[['AIR Analytics — synthetic demo data'],['From UTC',from,'Through UTC',to,'System',system,'Current status',status],['Opened',String(m.opened),'Cleared',String(m.cleared),'Opening backlog',String(m.backlogStart),'Closing backlog',String(m.backlogEnd)],['Cohort clearance %',m.clearanceRate===null?'N/A':String(m.clearanceRate),'Mean resolution minutes',m.meanMinutes===null?'N/A':String(m.meanMinutes)],[],[groupBy,'Opened cohort total','Currently open','Currently resolved'],...groups.map(g=>[g.label,String(g.total),String(g.open),String(g.resolved)]),[],['Date UTC','Opened','Cleared','Closing backlog'],...m.days.map(d=>[d.date,String(d.opened),String(d.cleared),String(d.backlog)]),[],['Incidents opened in period','Title','System','Current status','Opened at UTC','Resolved at UTC'],...cohort.map(r=>[r.id,r.title,r.service,r.status,r.openedAt,r.resolvedAt||''])];const blob=new Blob(['\uFEFF'+data.map(row=>row.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='AIR-analytics-report.csv';a.click();URL.revokeObjectURL(url);setNotice('Analytics report exported with metrics, grouped summary, daily data, and incident details.');};
 const statuses=['Declared','Investigating','Monitoring','Resolved'].map((label,i)=>({label,count:cohort.filter(r=>r.status===label).length,color:colors[i]}));
 const max=Math.max(1,...(m?.days.flatMap(d=>[d.opened,d.cleared])||[]));
 let cumulative=0;const donut= statuses.map(s=>{const start=cumulative;cumulative+=s.count/Math.max(1,cohort.length)*100;return `${s.color} ${start}% ${cumulative}%`;}).join(',');
 const width=620,height=200;const x=(i:number)=>40+(i+.5)*550/Math.max(1,m?.days.length||1);const y=(n:number)=>height-25-n/max*145;
 return <><div className="ops-heading"><div><span className="air-eyebrow">INCIDENT PERFORMANCE</span><h1>Analytics</h1><p>Incident demand, clearance, and the work still outstanding.</p></div><span className="ops-live">Synthetic data · snapshot Sep 8, 2026</span></div>
 <section className="air-card leadership-filters"><TextField size="small" type="date" label="From (UTC)" value={from} onChange={e=>setFrom(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField size="small" type="date" label="Through (UTC)" value={to} onChange={e=>setTo(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField size="small" select label="System" value={system} onChange={e=>setSystem(e.target.value)}><MenuItem value="All">All systems</MenuItem>{systems.map(s=><MenuItem key={s.id} value={s.id}>{s.name}</MenuItem>)}</TextField><TextField size="small" select label="Current status" value={status} onChange={e=>setStatus(e.target.value)}>{['All','Declared','Investigating','Monitoring','Resolved'].map(s=><MenuItem key={s} value={s}>{s==='All'?'All statuses':s}</MenuItem>)}</TextField><Button onClick={()=>{setFrom('2026-09-02');setTo('2026-09-08');}}>Last 7 days</Button><Button onClick={()=>{setFrom('2026-08-10');setTo('2026-09-08');}}>Last 30 days</Button><Button variant="contained" onClick={exportReport} disabled={!m||to>'2026-09-08'||!m.days.some(d=>d.opened||d.cleared||d.backlog)}>Generate CSV report</Button><p className="air-config-note">Filters apply to all charts and reports. Status uses the current demo snapshot; date filters use opening and resolution events as labeled.</p></section>{notice&&<p role="status" className="air-success">{notice}</p>}
 {!m||to>'2026-09-08'?<div className="air-card" role="alert">Choose a valid range of up to 93 days ending on or before the demo snapshot, September 8, 2026.</div>:<>
 <div className="ops-metrics">{[['Incidents occurred',m.opened,'Opened in the selected period'],['Incidents cleared',m.cleared,'Resolved in the selected period'],['Outstanding incidents',m.backlogEnd,'Backlog at the end of the period'],['Cohort clearance',m.clearanceRate===null?'—':Math.round(m.clearanceRate)+'%','Opened in period, resolved by period end']].map(([label,value,description])=><div className="ops-metric" key={label}><span>{label}</span><strong>{value}</strong><small>{description}</small></div>)}</div>
 <div className="leadership-grid"><section className="air-card"><div className="air-section-title"><div><h3>Incident status</h3><span className="ops-live">Current status of incidents opened in period</span></div><TextField select size="small" label="Chart" value={statusChart} onChange={e=>setStatusChart(e.target.value)}>{['Donut','Bars'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></div>{!cohort.length?<p className="ops-empty">No incidents opened in this period.</p>:<div className="leadership-status">{statusChart==='Donut'&&<div className="leadership-donut" style={{background:`conic-gradient(${donut})`}} role="img" aria-label={statuses.map(s=>`${s.label}: ${s.count}`).join(', ')}><div><strong>{cohort.length}</strong><span>incidents</span></div></div>}<div className="leadership-legend">{statuses.map(s=><div key={s.label}><span><i style={{background:s.color}}/>{s.label}</span><strong>{s.count}</strong>{statusChart==='Bars'&&<div className="leadership-bar"><span style={{width:`${s.count/Math.max(1,cohort.length)*100}%`,background:s.color}}/></div>}</div>)}</div></div>}</section>
 <section className="air-card"><div className="air-section-title"><div><h3>Opened vs. cleared</h3><span className="ops-live">Daily incident events · UTC</span></div><TextField select size="small" label="Chart" value={trendChart} onChange={e=>setTrendChart(e.target.value)}>{['Bars','Lines'].map(s=><MenuItem key={s} value={s}>{s}</MenuItem>)}</TextField></div><svg className="leadership-trend" viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`Daily incidents: ${m.opened} opened and ${m.cleared} cleared; exact values in the chart data table.`}>{[0,1,2].map(i=><g key={i}><line x1="36" x2="600" y1={y(max*i/2)} y2={y(max*i/2)} stroke="#ecedee"/><text x="25" y={y(max*i/2)+4} textAnchor="end" fill="#53565a" fontSize="12">{Number((max*i/2).toFixed(1))}</text></g>)}{trendChart==='Bars'?m.days.map((d,i)=><g key={d.date}><rect x={x(i)-Math.min(10,180/m.days.length)} y={y(d.opened)} width={Math.min(9,170/m.days.length)} height={175-y(d.opened)} fill="#006fcf"><title>{d.date}: {d.opened} opened</title></rect><rect x={x(i)+1} y={y(d.cleared)} width={Math.min(9,170/m.days.length)} height={175-y(d.cleared)} fill="#008767"><title>{d.date}: {d.cleared} cleared</title></rect></g>):['opened','cleared'].map((key,k)=><polyline key={key} points={m.days.map((d,i)=>`${x(i)},${y(d[key as 'opened'|'cleared'])}`).join(' ')} fill="none" stroke={k?'#008767':'#006fcf'} strokeWidth="2.5"/>)}<text x="40" y="198" fill="#53565a" fontSize="12">{from}</text><text x="595" y="198" textAnchor="end" fill="#53565a" fontSize="12">{to}</text></svg><div className="leadership-chart-key"><span><i style={{background:'#006fcf'}}/>Opened</span><span><i style={{background:'#008767'}}/>Cleared</span></div></section>
 <section className="air-card"><h3>Clearance balance</h3><p className="air-config-note">Opening backlog + new incidents − cleared incidents = closing backlog.</p><div className="leadership-balance">{[['Opening backlog',m.backlogStart],['Opened',m.opened],['Cleared',m.cleared],['Closing backlog',m.backlogEnd]].map(([label,value],i)=><div key={label}><small>{label}</small><strong>{i===2?'−':''}{value}</strong><div className="leadership-bar"><span style={{width:`${Number(value)/Math.max(1,m.backlogStart,m.opened,m.cleared,m.backlogEnd)*100}%`,background:i===2?'#008767':'#006fcf'}}/></div></div>)}</div><p className="air-config-note">{m.backlogEnd>m.backlogStart?`Backlog grew by ${m.backlogEnd-m.backlogStart}. Review capacity and the oldest unresolved incidents.`:m.backlogEnd<m.backlogStart?`Backlog reduced by ${m.backlogStart-m.backlogEnd}.`:'Backlog is unchanged across this period.'}</p></section>
 <section className="air-card"><h3>Resolution efficiency</h3><div className="leadership-efficiency"><strong>{m.meanMinutes===null?'—':Math.round(m.meanMinutes)}<small>{m.meanMinutes===null?'No resolutions in period':'minutes · mean time to resolution'}</small></strong></div><p className="air-config-note">Measured from declaration to resolution for the {m.cleared} incidents cleared in this period. Unresolved incidents are excluded.</p><div className="air-callout">{m.cleared<5?'Small sample: interpret this result alongside backlog and severity.':'Review severity mix before comparing resolution times across teams.'} Clearance measures recovery, not completion of all preventive actions.</div></section></div>
 <section className="ops-table-panel"><div className="ops-panel-heading"><h2>Incident report summary</h2><TextField size="small" select label="Group by" value={groupBy} onChange={e=>setGroupBy(e.target.value as typeof groupBy)}>{['System','Status','Date'].map(g=><MenuItem key={g} value={g}>{g}</MenuItem>)}</TextField></div><TableContainer><Table aria-label="Grouped incident report"><TableHead><TableRow>{[groupBy,'Opened in period','Currently open','Currently resolved'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{groups.map(g=><TableRow key={g.label}><TableCell>{g.label}</TableCell><TableCell>{g.total}</TableCell><TableCell>{g.open}</TableCell><TableCell>{g.resolved}</TableCell></TableRow>)}{!groups.length&&<TableRow><TableCell colSpan={4}>No incidents opened in this scope.</TableCell></TableRow>}</TableBody></Table></TableContainer></section>
 <section className="ops-table-panel"><div className="ops-panel-heading"><h2>Incident details</h2><span className="ops-live">Opened in selected period</span></div><TableContainer><Table aria-label="Analytics incident details"><TableHead><TableRow>{['Incident','System','Status','Severity','Opened (UTC)','Resolved (UTC)'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{cohort.map(r=><TableRow key={r.id}><TableCell><small className="ops-id">{r.id}</small>{r.title}</TableCell><TableCell>{r.service}</TableCell><TableCell>{r.status}</TableCell><TableCell>{r.severity}</TableCell><TableCell>{r.openedAt.replace('T',' ').replace('Z','')}</TableCell><TableCell>{r.resolvedAt?.replace('T',' ').replace('Z','')||'Unresolved'}</TableCell></TableRow>)}{!cohort.length&&<TableRow><TableCell colSpan={6}>No matching incidents.</TableCell></TableRow>}</TableBody></Table></TableContainer></section>
 <details className="air-card"><summary>View daily chart data</summary><TableContainer><Table size="small" aria-label="Analytics daily chart data"><TableHead><TableRow>{['Date (UTC)','Opened','Cleared','Closing backlog'].map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{m.days.map(d=><TableRow key={d.date}><TableCell>{d.date}</TableCell><TableCell>{d.opened}</TableCell><TableCell>{d.cleared}</TableCell><TableCell>{d.backlog}</TableCell></TableRow>)}</TableBody></Table></TableContainer></details>
 </>}</>;
}
