import { Fragment, useState } from 'react';
import { Button, TextField, MenuItem, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Dialog, DialogTitle, DialogContent, DialogActions } from '@mui/material';
import { ArrowForwardRounded, SearchRounded, GraphicEqRounded, BoltRounded, CheckCircleOutlineRounded, ArrowOutwardRounded, FilterListRounded, ScheduleRounded, ExpandMoreRounded, ChevronRightRounded } from '@mui/icons-material';
import { incidentRows, filterRows } from '../data/incidents';
import type { LiveAlertRow, LiveIncidentRow } from '../types/investigation';

type Props = { page: string; recovered: boolean; reviewed: boolean; openIncident: (stage: number) => void; liveIncidentRows: LiveIncidentRow[]; liveAlertRows: LiveAlertRow[]; onOpenLive: (key: string) => void };
export function OperationsPage({ page, recovered, reviewed, openIncident, liveIncidentRows, liveAlertRows, onOpenLive }: Props) {
  const [expanded, setExpanded] = useState<string[]>([]);
  const [channel, setChannel] = useState<(typeof incidentRows)[number] | null>(null);
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All');
  const [severity, setSeverity] = useState('All');
  const [selected, setSelected] = useState<(typeof incidentRows)[number] | null>(null);
  const isOverview = page === 'Overview';
  const isAlerts = page === 'Alerts';
  const isReports = page === 'Post-mortems';
  const rows = liveIncidentRows;
  const visible = filterRows(rows, query, status, severity);
  const active = rows.filter(row => row.status === 'Investigating').length;
  const cleared = rows.filter(row => row.status === 'Investigated').length;
  const outstanding = rows.filter(row => row.status !== 'Investigated').length;
  const alerts = liveAlertRows;
  const alertsVisible = filterRows(alerts, query, status, severity);
  const liveIds = new Set(liveIncidentRows.map(row => row.id));
  const reports = [
          {id:'PM-2048',title:'Checkout availability degradation',incident:'INC-2048',owner:'Sam Chen',severity:'SEV 1',status:recovered ? reviewed?'Reviewed':'Draft' : 'Awaiting recovery',date:'Sep 7, 2026'},
          {id:'PM-2039',title:'Inventory cache refresh failure',incident:'INC-2039',owner:'Alex Rivera',severity:'SEV 3',status:'Published',date:'Sep 6, 2026'},
        ];
  const reportsVisible = filterRows(reports, query, status, severity);
  const openRow = (row: typeof incidentRows[number]) => liveIds.has(row.id) ? onOpenLive(row.id) : row.id === 'INC-2048' ? openIncident(isReports ? 3 : 0) : setSelected(row);
  const shownCount = isAlerts ? alertsVisible.length : isReports ? reportsVisible.length : visible.length;
  return <>
    <div className="ops-heading"><div><h1>{isOverview ? 'Operations overview' : page}</h1><p>{isOverview ? 'Your services, signals, and response — in one place.' : isAlerts ? 'A focused view of the signals that need attention.' : isReports ? 'Capture what happened. Improve what happens next.' : 'Track impact, coordinate response, and follow the evidence.'}</p></div><span className="ops-date"><ScheduleRounded fontSize="small" /> September 7, 2026 <span>UTC</span></span></div>
    {isOverview && <>
      <div className="ops-metrics">{[{label:'Active incidents',value:active.toString().padStart(2,'0'),detail:'Declared or under investigation',icon:<BoltRounded />,tone:'red'}, {label:'Incidents cleared',value:cleared.toString().padStart(2,'0'),detail:'Resolved in the demo snapshot',icon:<CheckCircleOutlineRounded />,tone:'green'}, {label:'Outstanding incidents',value:outstanding.toString().padStart(2,'0'),detail:'All unresolved, including monitoring',icon:<GraphicEqRounded />,tone:'blue'}, {label:'Incident clearance rate',value:rows.length ? `${Math.round(cleared / rows.length * 100)}%` : '—',detail:'Resolved ÷ total incidents · demo snapshot',icon:<CheckCircleOutlineRounded />,tone:'purple'}].map(metric => <div className="ops-metric" key={metric.label}><span className={`ops-metric-icon ${metric.tone}`}>{metric.icon}</span><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.detail}</small></div>)}</div>
      <div className="ops-focus"><div className="ops-focus-mark"><GraphicEqRounded /></div><div><span className="air-eyebrow">{recovered ? 'RECOVERY VERIFIED' : 'AIR INVESTIGATION · INC-2048'}</span><h2>{recovered ? 'Checkout is healthy. Capture the learning.' : 'Checkout errors point to a recent configuration change.'}</h2><p>{recovered ? 'Review the response timeline and assign prevention actions.' : 'Four evidence sources connect pool saturation to deployment v2.18.0.'}</p></div><Button variant="contained" endIcon={<ArrowForwardRounded />} onClick={() => openIncident(recovered ? 3 : 0)}>{recovered ? 'Review post-mortem' : 'Open investigation'}</Button></div>
    </>}
    <section className="ops-table-panel">
      <div className="ops-panel-heading"><div><h2>{isOverview ? 'Incident activity' : isAlerts ? 'Alert inbox' : isReports ? 'Incident reviews' : 'All incidents'} <span className="ops-count">{isAlerts ? alerts.length : isReports ? reports.length : rows.length}</span></h2>{isOverview && <p>Current response and recently resolved incidents.</p>}</div>{isOverview ? <span className="ops-live"><span className="green-dot" /> Demo snapshot · 09:46</span> : <span className="ops-live">Synthetic demonstration records</span>}</div>
      <div className="ops-filters"><TextField size="small" placeholder={isAlerts ? 'Search alerts…' : isReports ? 'Search post-mortems…' : 'Search incidents…'} value={query} onChange={e=>setQuery(e.target.value)} slotProps={{ input: { startAdornment:<SearchRounded fontSize="small"/> }, htmlInput:{'aria-label':'Search records'} }}/><TextField select size="small" label="Status" value={status} onChange={e=>setStatus(e.target.value)}>{(isAlerts ? ['All','Firing','Acknowledged','Investigating','Investigated','Failed','Resolved'] : isReports ? ['All','Awaiting recovery','Draft','Reviewed','Published'] : ['All','Acknowledged','Investigating','Investigated','Declared','Monitoring','Failed','Resolved']).map(s=><MenuItem key={s} value={s}>{s === 'All' ? 'All statuses' : s}</MenuItem>)}</TextField><TextField select size="small" label="Severity" value={severity} onChange={e=>setSeverity(e.target.value)}>{['All','SEV 1','SEV 2','SEV 3'].map(s=><MenuItem key={s} value={s}>{s === 'All' ? 'All severities' : s}</MenuItem>)}</TextField>{query || status !== 'All' || severity !== 'All' ? <Button onClick={()=>{setQuery('');setStatus('All');setSeverity('All');}}>Clear filters</Button> : <span className="ops-filter-hint"><FilterListRounded fontSize="small" /> Filter view</span>}</div>
      <TableContainer><Table aria-label={isAlerts ? 'Alerts' : isReports ? 'Post-mortems' : 'Incidents'}><TableHead><TableRow>{(isAlerts ? ['Alert group','Source','Service','Incident ID','Severity','Status'] : isReports ? ['Post-mortem','Incident','Owner','Severity','Status','Created'] : ['Severity','Incident','Affected service','Slack channel','Duration','Responders','Status']).map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>
        {!isAlerts && !isReports && visible.map(row=><TableRow hover key={row.id}><TableCell><span className={`ops-badge sev-${row.severity.slice(-1)}`}>{row.severity}</span></TableCell><TableCell><small className="ops-id">{row.id} <span>· {row.time}</span></small><button className="ops-row-link" onClick={()=>openRow(row)}>{row.title}</button></TableCell><TableCell><span className="ops-service">{row.service}</span></TableCell><TableCell><button className="air-channel-link" onClick={()=>setChannel(row)}>#{row.slackChannel}</button><small className="ops-id">Created with incident · demo</small></TableCell><TableCell>{row.duration}</TableCell><TableCell><div className="ops-responders"><span className="air-avatar small">{row.owner.split(' ').map(n=>n[0]).join('')}</span><span>{row.owner}</span></div></TableCell><TableCell><span className={`ops-status ${row.status.toLowerCase()}`}><i/>{row.status}</span></TableCell></TableRow>)}
        {isAlerts && alertsVisible.map(row=>{const isExpanded=expanded.includes(row.id); return <Fragment key={row.id}><TableRow hover><TableCell><button className="air-alert-toggle" aria-expanded={isExpanded} aria-controls={`children-${row.eventId}`} onClick={()=>setExpanded(ids=>ids.includes(row.id)?ids.filter(id=>id!==row.id):[...ids,row.id])}>{isExpanded?<ExpandMoreRounded/>:<ChevronRightRounded/>}<span><strong>{row.title}</strong><small>{row.occurrences.length} {row.occurrences.length===1?'occurrence':'similar occurrences'} · {row.environment} · {row.region}</small></span></button></TableCell><TableCell>{row.source}</TableCell><TableCell><span className="ops-service">{row.service}</span></TableCell><TableCell><button className="air-channel-link" onClick={()=>liveIds.has(row.incidentId)?onOpenLive(row.incidentId):openIncident(0)}>{row.incidentId}</button></TableCell><TableCell><span className={`ops-badge sev-${row.severity.slice(-1)}`}>{row.severity}</span></TableCell><TableCell><span className={`ops-status ${row.status.toLowerCase()}`}><i/>{row.status}</span></TableCell></TableRow><TableRow hidden={!isExpanded} id={`children-${row.eventId}`} className="air-alert-children"><TableCell colSpan={6}><ul aria-label={`Occurrences of ${row.title}`}>{row.occurrences.map(event=><li key={event.eventId}><span className="air-tree-branch"/><strong>{event.eventId}</strong><span>{event.instance}</span><time>{event.observedAt} UTC</time><span className="ops-service">{event.source}</span></li>)}</ul><p>Same alert fingerprint, service, environment, and region. Repeated deliveries of the same source event appear only once.</p></TableCell></TableRow></Fragment>})}
        {isReports && reportsVisible.map(row=><TableRow hover key={row.id}><TableCell><small className="ops-id">{row.id}</small><button className="ops-row-link" onClick={()=>row.id==='PM-2048'?openIncident(3):setSelected(incidentRows[3])}>{row.title}</button></TableCell><TableCell>{row.incident}</TableCell><TableCell>{row.owner}</TableCell><TableCell><span className={`ops-badge sev-${row.severity.slice(-1)}`}>{row.severity}</span></TableCell><TableCell><span className={`ops-status ${row.status.toLowerCase().replaceAll(' ','-')}`}><i/>{row.status}</span></TableCell><TableCell>{row.date}</TableCell></TableRow>)}
        {shownCount === 0 && <TableRow><TableCell colSpan={isAlerts||isReports?6:7} className="ops-empty">No matching records. Try a different search or clear the filters.<br/><Button onClick={()=>{setQuery('');setStatus('All');setSeverity('All');}}>Clear filters</Button></TableCell></TableRow>}
      </TableBody></Table></TableContainer>
      <div className="ops-table-footer"><span>{shownCount} {shownCount === 1 ? 'record' : 'records'} · synthetic demo data</span><span>All times in UTC</span></div>
    </section>
    <Dialog open={channel!==null} onClose={()=>setChannel(null)} maxWidth="sm" fullWidth><DialogTitle>#{channel?.slackChannel}</DialogTitle><DialogContent><p><strong>Channel ready · simulated</strong></p><p>Created alongside {channel?.id} at {channel?.time}. Incident owner: {channel?.owner}.</p><p>The production design provisions one Slack channel per incident in parallel with investigation startup. Channel failures must not block investigation; retries reuse the incident ID to avoid duplicate channels.</p><p>No Slack workspace is connected and no channel or message has been created externally.</p></DialogContent><DialogActions><Button onClick={()=>setChannel(null)}>Close</Button></DialogActions></Dialog>
    <Dialog open={selected!==null} onClose={()=>setSelected(null)} maxWidth="sm" fullWidth><DialogTitle>{selected?.title}</DialogTitle><DialogContent><p>{selected?.id} · {selected?.service} · {selected?.status}</p><p>{selected?.summary}</p><p><strong>Owner:</strong> {selected?.owner}</p><p>This is a read-only sample record. Open INC-2048 to explore the complete interactive response workflow.</p></DialogContent><DialogActions><Button onClick={()=>setSelected(null)}>Close</Button><Button endIcon={<ArrowOutwardRounded/>} onClick={()=>{setSelected(null);openIncident(0);}}>Explore INC-2048</Button></DialogActions></Dialog>
  </>;
}
