import { InvestigationSummary } from './InvestigationSummary';
import { toScenario, type IntakeIncident } from '../api/alertIntake';
import { useState } from 'react';
import { formatUtc } from '../data/liveScenarios';
import type { InvestigationResponse, LiveStatus } from '../types/investigation';
import './SlackChannelPage.css';

type Props = { incidents: IntakeIncident[]; loadError: string; statuses: Record<string, LiveStatus>; results: Record<string, InvestigationResponse>; errors: Record<string, string>; onPortal: () => void };
export function SlackChannelPage({ incidents, loadError, statuses, results, errors, onPortal }: Props) {
  const liveScenarios = incidents.map(toScenario);
  const [search, setSearch] = useState('');
  const [channel, setChannel] = useState('all');
  const [thread, setThread] = useState<string | null>(null);
  const selected = liveScenarios.find(s => s.key === thread);
  const result = thread ? results[thread] : undefined;
  const filtered = liveScenarios.filter(s => (channel === 'all' || s.key === channel) && `${s.title} ${s.service} ${s.key}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="air-chat">
    <div className="air-chat-top"><a href="/" className="air-chat-brand" onClick={e => { e.preventDefault(); onPortal(); }}>✳ AIR <span>workspace</span></a><input aria-label="Search incidents" placeholder="Search incidents, services, or incident IDs" value={search} onChange={e => setSearch(e.target.value)}/><span className="air-chat-demo">Slack-style demo</span></div>
    <div className="air-chat-layout"><nav className="air-chat-sidebar" aria-label="Incident channels"><h2>SRE workspace</h2><p><i/> AIR incident response</p><div className="air-chat-nav-label">CHANNELS</div><button aria-current={channel === 'all' ? 'page' : undefined} onClick={() => setChannel('all')}># air-incidents</button>{liveScenarios.map(s => <button key={s.key} aria-current={channel === s.key ? 'page' : undefined} onClick={() => setChannel(s.key)}># {s.slackChannel}</button>)}<div className="air-chat-sidebar-bottom"><strong>Context to action.</strong><p>View the signal here.<br/>Investigate with AIR.</p><button onClick={onPortal}>Open AIR portal ↗</button></div></nav>
    <main className="air-chat-main"><header className="air-chat-channel-header"><div><h1># {channel === 'all' ? 'air-incidents' : liveScenarios.find(s => s.key === channel)?.slackChannel}</h1><p>Alerts, incident context, and investigation updates in one place.</p></div></header><div className="air-chat-banner"><span>✦</span><div><strong>Your incident response starts here</strong><p>Source System → Validated alert → Create / Update Incident → Channel notification · Investigation Details opens AIR in a new tab, where you can start the live investigation.</p></div></div><div className="air-chat-feed">{loadError && <p role="alert">{loadError}</p>}<div className="air-chat-divider"><span>Live notification feed · {filtered.length} incidents</span></div>{!filtered.length && <div className="air-chat-empty"><h2>{loadError ? 'Connection unavailable' : search ? 'No matching incidents' : 'Waiting for your first alert'}</h2><p>{loadError || 'Send an ELF, UI, or Grafana request from Postman. New incidents appear here automatically.'}</p></div>}{filtered.map(s => <article className="air-chat-message" key={s.key}><div className="air-chat-avatar">✳</div><div className="air-chat-message-content"><div className="air-chat-author"><strong>AIR</strong><span>APP</span><time>{formatUtc(s.request.incident.detected_at)}</time></div><p><strong>@{s.owner}</strong> · {s.alertSource} detected an issue in {s.service}.</p><div className="air-chat-card"><div className="air-chat-card-meta"><span className="air-chat-severity">{s.request.incident.severity}</span><span>{s.key}</span><span className="air-chat-status">{statuses[s.key] ?? 'Open'}</span></div><h2>{s.title}</h2><p>{s.request.incident.description}</p><dl><div><dt>Service</dt><dd>{s.service}</dd></div><div><dt>Environment</dt><dd>{s.request.incident.environment}</dd></div></dl><p><strong>Related alerts:</strong> {incidents.find(i => i.id === s.key)?.alertCount} · <strong>Rule:</strong> {incidents.find(i => i.id === s.key)?.rule}</p><p><strong>Last update:</strong> {formatUtc(incidents.find(i => i.id === s.key)!.updatedAt)}</p><div className="air-chat-actions"><a className="air-chat-primary" href={`/incidents/${s.key}/investigation`} target="_blank" rel="noopener noreferrer" title="Open investigation in a new tab">Investigation Details ↗</a><button onClick={() => setThread(s.key)}>View thread →</button></div></div><button className="air-chat-thread-link" onClick={() => setThread(s.key)}>☷ View investigation summary & evidence</button></div></article>)}</div><footer className="air-chat-feed-footer">Persisted alerts · Updates every 2 seconds · Local Slack-style channel</footer></main>
    {selected && <aside className="air-chat-thread" aria-label="Incident thread"><header><div><h2>Thread</h2><span>{selected.key}</span></div><button aria-label="Close thread" onClick={() => setThread(null)}>✕</button></header><div className="air-chat-thread-body"><h3>{selected.title}</h3><h4>Alert details</h4>{incidents.find(i => i.id === selected.key)?.alerts.map(a => <div className="air-chat-evidence" key={`${a.source}:${a.eventId}`}><strong>{a.source} · {a.eventId}</strong><p>{a.summary}</p><p>{a.description}</p><p>{a.severity} · {a.environment} · {formatUtc(a.observedAt)}</p></div>)}<span className="air-chat-status">{statuses[selected.key] ?? 'Open'}</span>{errors[selected.key] && <p role="alert">{errors[selected.key]}</p>}{result ? <InvestigationSummary result={result}/> : <p>{statuses[selected.key] === 'Investigating' ? 'AIR is investigating. Results will appear here when the request completes.' : 'No investigation results yet. Open Investigation Details and start the investigation in AIR.'}</p>}<a className="air-chat-primary" href={`/incidents/${selected.key}/investigation`} target="_blank" rel="noopener noreferrer" title="Open investigation in a new tab">Investigation Details ↗</a></div></aside>}
    </div></div>;
}
