import { useState } from 'react';
import { Button, Chip, TextField, Table, TableHead, TableBody, TableRow, TableCell, TableContainer } from '@mui/material';
import { postmortemSections, postmortemMarkdown, postmortemHtml } from '../data/postmortemContent';
import type { ReportEvidence } from '../data/postmortemContent';
export function PostmortemReview({summary,reason,evidence,reviewed,onSummary,onReview}:{summary:string;reason:string;evidence:ReportEvidence[];reviewed:boolean;onSummary:(s:string)=>void;onReview:()=>void}){
 const [editing,setEditing]=useState(false);const sections=postmortemSections(summary,reason,evidence,reviewed);
 const download=(format:'md'|'html')=>{const content=format==='md'?postmortemMarkdown(sections,reviewed):postmortemHtml(sections,reviewed);const blob=new Blob([content],{type:format==='md'?'text/markdown;charset=utf-8':'text/html;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`AIR-INC-2048-Post-Incident-Review.${format}`;a.click();URL.revokeObjectURL(url);};
 return <article className="air-review-document"><header className="air-review-cover"><div className="air-section-title"><span className="air-eyebrow">AIR / INCIDENT REVIEW</span><Chip size="small" label={reviewed?'Reviewed in prototype':'Draft · human review required'}/></div><h2>Checkout availability degradation</h2><p>Post-Incident Review · INC-2048</p><div className="air-review-facts"><span>SEV 1</span><span>September 7, 2026</span><span>Sam Chen · Commander</span><span>Production · us-east-1</span></div><div className="air-button-row"><Button variant="contained" disabled={reviewed||!summary.trim()} onClick={()=>{onReview();setEditing(false);}}>{reviewed?'Review complete':'Mark reviewed'}</Button><Button variant="outlined" onClick={()=>download('html')}>Download formatted report</Button><Button onClick={()=>download('md')}>Export Markdown</Button></div><p className="air-config-note">Synthetic scenario. The formatted HTML report can be opened in a browser and printed to PDF.</p></header><nav className="air-review-contents" aria-label="Report contents">{sections.map((s,i)=><a key={s.id} href={`#review-${s.id}`}>{String(i+1).padStart(2,'0')} {s.title}</a>)}</nav>{sections.map((s,i)=><section className="air-review-section" id={`review-${s.id}`} key={s.id}><div className="air-section-title"><h3><span>{String(i+1).padStart(2,'0')}</span>{s.title}</h3>{i===0&&<Button size="small" onClick={()=>setEditing(!editing)}>{editing?'Done editing':'Edit summary'}</Button>}</div>{i===0&&editing?<TextField fullWidth multiline minRows={5} label="Executive summary" value={summary} onChange={e=>onSummary(e.target.value)}/>:null}{s.paragraphs.map((p,index)=>i===0&&index===0&&editing?null:<p key={index}>{p}</p>)}{s.id==='timeline'?<ol className="air-review-progress" aria-label="Incident response milestones">{s.rows!.map((r,j)=><li key={r[1]} className={r[3]==='Awaiting review'?'pending':r[3]==='Provisional'?'provisional':'complete'}><span className="air-review-progress-marker">{r[3]==='Awaiting review'?j+1:r[3]==='Provisional'?'!':'✓'}</span><div><div className="air-review-progress-meta"><time>{r[0]} UTC</time><span>{r[3]}</span></div><h4>{r[1]}</h4><p>{r[2]}</p></div></li>)}</ol>:s.headers&&<TableContainer><Table size="small" aria-label={s.title}><TableHead><TableRow>{s.headers.map(h=><TableCell key={h}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{s.rows!.map((r,j)=><TableRow key={j}>{r.map((c,k)=><TableCell key={k}>{c}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer>}</section>)}<footer className="air-review-end">End of review · {sections.length} sections · Evidence and uncertainties preserved</footer></article>;
}
